---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "Brandon Bennett"
jupyter: python3
format:
  html:
    theme: darkly
    page-layout: full
    self-contained: true
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: "Grand Questions"
    number-sections: true
    code-fold: true
    code-summary: "See Code"
    code-overflow: wrap
    code-copy: hover
    code-wrap: true
    code-line-numbers: true
    code-tools:
      toggle: true
      caption: See Code
execute:
  warning: false
editor:
  render-on-save: true
---

# Elevator Pitch {.unnumbered}

-   My name, *Brandon*, was given to me right after its peak of popularity in *1995*
-   Most *Brittany's* were born in the *late 80's and early 90's*, making them around *35 years old*
-   *Marth, Mary, Paul, and Peter* could have been influenced by the [*Healing Revival Movement*](https://en.wikipedia.org/wiki/Healing_revival) after WW2
    -   *Martha* was most popular in *1947*
    -   *Mary* was most popular in *1950*
    -   *Paul* was most popular in *1954*
    -   *Peter* was most popular in *1956*
-   The name *Rick* gained a lot of traction after the release of *[Casablanca](https://en.wikipedia.org/wiki/Casablanca_(film))* in *1942*
    -   *Rick* reached peak popularity in *1958*

```{python}
# | label: libraries
# | include: false
import numpy as np
import pandas as pd
import plotly.express as px
```

```{python}
# | label: fetch-data
# | fig-cap: Sample of the data

file = "https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"
# Reading in the data
df = pd.read_csv(file)

# Filtering out the columns we want to keep
df = df[["name", "year", "Total"]]

# Renaming some columns for uniformity
df = df.rename(columns={"name": "Name", "year": "Year"})

# Changing the 'Total' column to an int because we can't have
# .5 kids named something
df = df.astype({"Total": "int32"})

# Changing the 'Total' column to an int because we can't have
# .5 kids named something
df = df.astype({"Total": "int32"})
```

# Hi, My Name is...

*Question: How does your name at your birth year compare to its use historically?*

My name is *Brandon* and I was born in 1995, right after the peak of the names popularity in 1994. This makes a lot sense due to the number of people I know with the same name. One semester, I was in a ward with five other *Brandon's* and even when I go to the Doctors office I sometimes have to give my middle name because my last name, *Bennett*, is super common too!

```{python}
# | code-summary: Filtering records for 'Brandon'
# | warning: false

my_name = df.query("Name == 'Brandon'")
rows, cols = my_name.shape
```

The name *Brandon* has `{python} rows` records in our database.

```{python}
# | code-summary: Visualizing the data
# | fig-align: center
# | warning: false

fig = px.line(
    my_name,
    x='Year',
    y='Total',
    title="Popularity of 'Brandon'",
    labels={'Year': 'Year'}
)

# Adding a line to indicate my birth year
fig.add_vline(
    x=1995,
    label=dict(
        text="My Birthyear",
        textposition="middle left",
        font=dict(size=16)
    )
)

fig.show()
```

# Brittany

*If you talked to someone named Brittany on the phone, what is your guess of his or her age?*

I would guess that she is around ±35 years old. The majority of babies named *Brittany* falls right on 1990. Even when we look at popular media, there are a fair amount of actresses and singers with the first name *Brittany*, i.e. *Brittany Spears* (Pop Singer) and *Brittany Snow* (Actress)

*What ages would you not guess?*

I wouldn't guess anything above 50, not only because the data doesn't indicate that there are women named *Brittany* above that age, but I also know that's generally something to avoid when talking to women of any age.

```{python}
# | code-summary: Selecting all records of 'Brittany'
# | warning: false

brittany = df.query("Name == 'Brittany'")
rows, cols = brittany.shape
```

The name *Brittany* has `{python} rows` in our database.

```{python}
# | fig-cap: "Brittany is a relatively new name."
# | fig-align: center
# | warning: false

fig = px.line(
    brittany,
    x="Year",
    y="Total",
    title="Popularity of 'Brittany' over time",
    labels={"Year": "Year"},
)

fig.add_vline(
    x=1990,
    label=dict(text="Peak Brittany's", textposition="middle left", font=dict(size=16)),
)

fig.show()
```

# Christian Names

*Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?*

I notice there is a decent increase in all the names after *1945* and a steep decline in all of the names after the year *1960* or so. This falls right in line with the baby boomer demographic. This also makes a lot of sense, considering that a Gallup Poll Survey found that in 1950 [*over 90% of the adult population identified as Christian*](https://www.govinfo.gov/content/pkg/USCOURTS-ca4-15-02597/pdf/USCOURTS-ca4-15-02597-3.pdf). This fact seems to be supported by the trend of each name through the 1950's.

```{python}
# | code-summary: Filtering out Mary, Martha, Peter, and Paul
# | warning: false

names = ['Mary', 'Martha', 'Peter', 'Paul']
ch_names = df.query("Name in @names & (1920 <= Year <= 2000)")
```

```{python}
# | code-summary: Mary, Martha, Peter, and Paul
# | fig-cap: "Trend of Mary, Martha, Peter, and, Paul"
# | fig-align: center
# | warning: false

fig = px.line(
    ch_names,
    x="Year",
    y="Total",
    title="Mary, Martha, Paul, and, Peter",
    color="Name",
    labels={"Year": "Year", "Name": "Name"},
)

fig.add_vline(
    x=1947, line_dash="dash", line_color="blue", label=dict(text="Martha Peak")
)
fig.add_vline(x=1950, line_dash="dash", line_color="red", label=dict(text="Mary Peak"))
fig.add_vline(
    x=1954, line_dash="dash", line_color="green", label=dict(text="Paul Peak")
)
fig.add_vline(
    x=1956, line_dash="dash", line_color="purple", label=dict(text="Peter Peak")
)

fig.show()
```

# Rick

*Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?*

I chose the name *Rick* from *Casa Blanca*. *Casa Blanca* was released on *January 23, 1943*. The data seems to indicate that the movie had a significant impact on usage of the name *Rick*. The year this movie was released, there were only 193 babies given the name and there are no records before *1939*. The data seems to indicate that there was a significant impact from the movie.

```{python}
# | code-summary: Selecting 'Rick' from the database
# | warning: false

rick = df.query("Name == 'Rick'")
```

```{python}
# | code-summary: Plotting the name 'Rick'
# | fig-cap: "Trend of the name 'Rick'"
# | fig-align: center
# | warning: false

fig = px.line(
    rick,
    x='Year',
    y='Total',
    title="Popularity of 'Rick' over time",
    labels={
        'Year': 'Year'
    }
)

fig.add_vline(
    x=1942
)

fig.add_annotation(
    x=1942,
    y=5_000,
    text='Casa Blanca is released'
)

fig.show()
```
